version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start

  # Production service
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    restart: unless-stopped

  # Build service (for testing builds)
  app-build:
    build:
      context: .
      target: build
    volumes:
      - ./build:/app/build
